import IconPokebola from "@/components/icons/IconPokeBall";
import "./globals.css";

import type { Metadata } from "next";
import { Oxanium, Poppins } from 'next/font/google'

export const metadata: Metadata = {
  title: "PokeDex",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ['500', '700'],
  subsets: ['latin'],
  variable: '--font-poppins'
})

const oxanium = Oxanium({
  weight: ['500', '600'],
  subsets: ['latin'],
  variable: '--font-oxanium'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`${poppins.variable} ${oxanium.variable}`}>
      <body className="bg-red-700 px-6 max-w-5xl mx-auto overflow-hidden h-screen flex flex-col">
        <header className="py-6 flex items-center gap-2">
          <span className="animate-spin animate-infinite animate-duration-[5000ms] animate-delay-[5000ms] animate-ease-in-out animate-normal">
            <IconPokebola />
          </span>
          <h1 className="text-4xl font-heading font-bold text-white
          opacity-0 animate-fadeIn">
            PokeDex
          </h1>
        </header>
        <main>
          {children}
        </main>
        <footer>
          <div className="fixed bottom-0 py-6 flex items-center gap-2 bg-red-700 w-full">
            <h2>
              Feito Por Luiz Carlos
            </h2>
          </div>
        </footer>
      </body>
    </html>
  );
}
